
before_install:
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo add-apt-repository ppa:beineri/opt-qt591-trusty -y
 - sudo apt-get update -qq
 - sudo apt-get install qt59-meta-full -y
 
 install:
  - sudo apt-get remove g++
  - sudo apt-get install -qq g++-7
  
env: CXX="g++-7" CXXFLAGS="-std=c++14 -Wall -Wno-error"

before_script:
    - QTDIR="/opt/qt59"
    - PATH="$QTDIR/bin:$PATH"
    - source /opt/qt59/bin/qt59-env.sh

script: 
  - $CXX --version
  - g++-7 --version
  - qmake -qt=qt5 QtPaint.pro -r -spec linux-g++ CONFIG+=release
  - make -j9 CXX='g++-7' CXXFLAGS='-std=c++14 -Wall -Wno-error -fPIC'
  - ls -lhsa QtPaint
  
