language: generic

before_install:
 - sudo add-apt-repository ppa:beineri/opt-qt591-trusty --yes
 - sudo apt-get update -qq
 
install:
 - sudo apt-get install qt59-meta-full --yes
  
before_script:
    - QTDIR="/opt/qt59"
    - PATH="$QTDIR/bin:$PATH"
    - source /opt/qt59/bin/qt59-env.sh

script: 
  - qmake QtPaint.pro CONFIG+=release
  - make -j9 CXXFLAGS='-std=c++14 -Wall -Wno-error'
 
